// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void RN01TelaRequisioCampos() {
    driver.Navigate().GoToUrl("https://splendorous-starlight-c2b50a.netlify.app/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.Id("inpNumero")).Click();
    driver.FindElement(By.Id("inpNumero")).SendKeys("1");
    driver.FindElement(By.Id("idDepartamento")).Click();
    driver.FindElement(By.Id("idFuncionario")).Click();
    driver.FindElement(By.Id("idFuncionario")).SendKeys("1");
    driver.FindElement(By.Id("NomeFuncionario")).Click();
    driver.FindElement(By.Id("NomeFuncionario")).SendKeys("José");
    driver.FindElement(By.Id("dataRequisicao")).Click();
    driver.FindElement(By.Id("dataRequisicao")).SendKeys("2024-02-08");
    driver.FindElement(By.Id("urgente")).Click();
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("categoriaMotivo"));
      dropdown.FindElement(By.XPath("//option[. = 'RP']")).Click();
    }
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("categoriaMotivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Cliente']")).Click();
    }
    driver.FindElement(By.Id("Motivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Motivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Quebra de Máquina']")).Click();
    }
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).SendKeys("1");
    driver.FindElement(By.Id("Quantidade")).SendKeys("1");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("2");
    driver.FindElement(By.Id("Quantidade")).Click();
    {
      var element = driver.FindElement(By.Id("Quantidade"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("Quantidade")).SendKeys("3");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("4");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("5");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("6");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("7");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("8");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("9");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.CssSelector("#btn-gravar > span")).Click();
  }
}
