// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void RN11TelaRequisioBotoGravar() {
    driver.Navigate().GoToUrl("https://splendorous-starlight-c2b50a.netlify.app/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).SendKeys("1");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("21");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("18");
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("0");
    driver.FindElement(By.Id("Quantidade")).SendKeys("-1");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("-2");
    driver.FindElement(By.Id("Quantidade")).Click();
    driver.FindElement(By.Id("Quantidade")).SendKeys("-3");
    driver.FindElement(By.Id("Quantidade")).Click();
  }
}
